name: Deploy
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: skipcheck
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: echo "skipping github pages deploy [dependabot]"
      - name: Checkout ğŸ›ï¸
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: yarn
      - name: Build ğŸ”§
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: yarn build
      - name: Deploy ğŸš€
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: public
